{{- if .Values.gameServer.ports.udp }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gameServer.gameType }}-udp
  labels:
    app: {{ .Values.gameServer.gameType }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Values.gameServer.gameType }}
spec:
  type: {{ .Values.gameServer.serviceType }}
  ports:
  {{- if eq "LoadBalancer" .Values.gameServer.serviceType }}
  {{- range .Values.gameServer.ports.udp }}
  - name: {{ $.Values.gameServer.gameType }}-udp-{{ . }}
    port: {{ . }}
    targetPort: {{ $.Values.gameServer.gameType }}-udp-{{ . }}
    protocol: UDP
  {{- end }}
  {{- end }}
  selector:
    app: {{ .Values.gameServer.gameType }}
{{- end }}